[theme]
base="light"                  # أو "dark"
backgroundColor="#FAF3E0"     # اللون الذهبي الفاتح
primaryColor="#D69E2E"        # لون ثانوي للأزرار والروابط
secondaryBackgroundColor="#FAF3E0"
textColor="#000000"
font="sans serif"
